--DELETE OLD DATA
DELETE FROM AUTHOR;
DELETE FROM COMMENTS;
DELETE FROM NEWS;
DELETE FROM TAG;
DELETE FROM NEWS_AUTHORS;
DELETE FROM NEWS_TAG;

--ADD NEW DATA
BEGIN
  FOR i IN 1..10000 LOOP
    INSERT INTO NEWS (NEWS_ID, SHORT_TEXT, FULL_TEXT, TITLE, CREATION_DATE, MODIFICATION_DATE) VALUES (NEWS_SEQ.NEXTVAL,'SHORT ' || i, 'FULL ' || i,'TITLE ' || i, SYSDATE, SYSDATE);
  END LOOP;

  FOR i IN 1..100 LOOP
    INSERT INTO AUTHOR (AUTHOR_ID, NAME) VALUES (AUTHOR_SEQ.NEXTVAL, 'AUTHOR ' || i);
  END LOOP;
  
  FOR i IN 1..100000 LOOP
    INSERT INTO COMMENTS (COMMENT_ID, COMMENT_TEXT, CREATION_DATE, NEWS_ID) VALUES (COMMENTS_SEQ.NEXTVAL, 'COMMENT TEXT ' || i, SYSDATE, CEIL(i/10));
  END LOOP;
  
  FOR i IN 1..10 LOOP
    INSERT INTO TAG (TAG) VALUES ('tag ' || TAG_SEQ.NEXTVAL);
  END LOOP;
  
  FOR i IN 1..30000 LOOP
    INSERT INTO NEWS_AUTHORS (NEWS_ID, AUTHOR_ID) VALUES (CEIL(i / 3), MOD(i, 100) + 1);
  END LOOP;
  
  FOR i IN 1..20000 LOOP
    INSERT INTO NEWS_TAG (NEWS_ID, TAG) VALUES (CEIL(i / 2), 'tag ' || (MOD(i, 10) + 1));
  END LOOP;
  COMMIT WORK;
END;