--DROP PREVIOUS TABLES
DROP TABLE NEWS_AUTHORS;
DROP TABLE NEWS_TAG;
DROP TABLE AUTHOR;
DROP TABLE COMMENTS;
DROP TABLE NEWS;
DROP TABLE TAG;

--CREATE NEW TABLES
--CREATE TABLE NEWS
CREATE TABLE NEWS 
(
  NEWS_ID NUMBER(20) NOT NULL 
, SHORT_TEXT NVARCHAR2(100) NOT NULL 
, FULL_TEXT NVARCHAR2(2000) NOT NULL 
, TITLE NVARCHAR2(30) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, MODIFICATION_DATE DATE NOT NULL 
, CONSTRAINT NEWS_PK PRIMARY KEY 
  (
    NEWS_ID 
  )
  ENABLE 
);

--CREATE TABLE AUTHOR
CREATE TABLE AUTHOR 
(
  AUTHOR_ID NUMBER(20) NOT NULL 
, NAME NVARCHAR2(30) NOT NULL 
, CONSTRAINT AUTHOR_PK PRIMARY KEY 
  (
    AUTHOR_ID 
  )
  ENABLE 
);

--CREATE TABLE COMMNETS
CREATE TABLE COMMENTS 
(
  COMMENT_ID NUMBER(20) NOT NULL 
, COMMENT_TEXT NVARCHAR2(100) NOT NULL 
, CREATION_DATE DATE NOT NULL 
, NEWS_ID NUMBER(20) NOT NULL 
, CONSTRAINT COMMENTS_PK PRIMARY KEY (COMMENT_ID)
, CONSTRAINT "COMMENTS_FK1" FOREIGN KEY ("NEWS_ID")
    REFERENCES "ROOT"."NEWS" ("NEWS_ID")
  ENABLE 
);

--CREATE TABLE TAG
CREATE TABLE TAG 
(
  TAG NVARCHAR2(100) NOT NULL 
, CONSTRAINT TAG_PK PRIMARY KEY 
  (
    TAG
  )
  ENABLE 
);

--CREATE TABLE NEWS_AUTHORS
CREATE TABLE NEWS_AUTHORS 
(
  NEWS_ID NUMBER(20) NOT NULL 
, AUTHOR_ID NUMBER(20) NOT NULL 
, CONSTRAINT NEWS_AUTHORS_UP UNIQUE (NEWS_ID, AUTHOR_ID) ENABLE
, CONSTRAINT "NEWS_AUTHORS_FK1" FOREIGN KEY ("AUTHOR_ID")
    REFERENCES "ROOT"."AUTHOR" ("AUTHOR_ID") ENABLE
, CONSTRAINT "NEWS_AUTHORS_FK2" FOREIGN KEY ("NEWS_ID")
    REFERENCES "ROOT"."NEWS" ("NEWS_ID") ENABLE
);

--CREATE TABLE NEWS_TAG 
CREATE TABLE NEWS_TAG 
(
  NEWS_ID NUMBER(20) NOT NULL 
, TAG NVARCHAR2(100) NOT NULL
, CONSTRAINT NEWS_TAG_UP UNIQUE (NEWS_ID, TAG) ENABLE
, CONSTRAINT "NEWS_TAG_FK1" FOREIGN KEY ("TAG")
    REFERENCES "ROOT"."TAG" ("TAG") ENABLE
, CONSTRAINT "NEWS_TAG_FK2" FOREIGN KEY ("NEWS_ID")
    REFERENCES "ROOT"."NEWS" ("NEWS_ID") ENABLE
);

--DROP PREVIOUS SEQUENCES
DROP SEQUENCE AUTHOR_SEQ;
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE NEWS_SEQ;
DROP SEQUENCE TAG_SEQ;

--CREATE SEQUENCES FOR ALL TABLES
CREATE SEQUENCE AUTHOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COMMENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE NEWS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TAG_SEQ START WITH 1 INCREMENT BY 1;